# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hisense/AD683G/setup-makefiles.sh

PRODUCT_COPY_FILES += \
 vendor/hisense/AD683G/proprietary/lib/libgsl.so:system/lib/libgsl.so \
 vendor/hisense/AD683G/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
 vendor/hisense/AD683G/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
 vendor/hisense/AD683G/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
 vendor/hisense/AD683G/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
 vendor/hisense/AD683G/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
 vendor/hisense/AD683G/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
 vendor/hisense/AD683G/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
 vendor/hisense/AD683G/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
 vendor/hisense/AD683G/proprietary/lib/liballjoyn.so:system/lib/liballjoyn.so \
 vendor/hisense/AD683G/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
 vendor/hisense/AD683G/proprietary/etc/AudioFilter.csv:system/etc/AudioFilter.csv \
 vendor/hisense/AD683G/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
 vendor/hisense/AD683G/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
 vendor/hisense/AD683G/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
 vendor/hisense/AD683G/proprietary/lib/libgemini.so:system/lib/libgemini.so \
 vendor/hisense/AD683G/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
 vendor/hisense/AD683G/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
 vendor/hisense/AD683G/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
 vendor/hisense/AD683G/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
 vendor/hisense/AD683G/proprietary/lib/libchromatix_ov5647_sunny_p5v02s_preview.so:system/lib/libchromatix_ov5647_sunny_p5v02s_preview.so \
 vendor/hisense/AD683G/proprietary/lib/libchromatix_ov5647_truly_cm6868_preview.so:system/lib/libchromatix_ov5647_truly_cm6868_preview.so \
 vendor/hisense/AD683G/proprietary/lib/libchromatix_ov5647_sunny_p5v02s_video_hfr.so:system/lib/libchromatix_ov5647_sunny_p5v02s_video_hfr.so \
 vendor/hisense/AD683G/proprietary/lib/libchromatix_ov5647_truly_cm6868_video_hfr.so:system/lib/libchromatix_ov5647_truly_cm6868_video_hfr.so \
 vendor/hisense/AD683G/proprietary/lib/libchromatix_ov5647_sunny_p5v02s_default_video.so:system/lib/libchromatix_ov5647_sunny_p5v02s_default_video.so \
 vendor/hisense/AD683G/proprietary/lib/libchromatix_ov5647_truly_cm6868_default_video.so:system/lib/libchromatix_ov5647_truly_cm6868_default_video.so \
 vendor/hisense/AD683G/proprietary/lib/libwidevine.so:system/lib/libwidevine.so \
 vendor/hisense/AD683G/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
 vendor/hisense/AD683G/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
 vendor/hisense/AD683G/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
 vendor/hisense/AD683G/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
 vendor/hisense/AD683G/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
 vendor/hisense/AD683G/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
 vendor/hisense/AD683G/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
 vendor/hisense/AD683G/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
 vendor/hisense/AD683G/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
 vendor/hisense/AD683G/proprietary/bin/amploader:system/bin/amploader \
 vendor/hisense/AD683G/proprietary/bin/dun-server:system/bin/dun-server \
 vendor/hisense/AD683G/proprietary/bin/sapd:system/bin/sapd \
 vendor/hisense/AD683G/proprietary/bin/sdptool:system/bin/sdptool \
 vendor/hisense/AD683G/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
 vendor/hisense/AD683G/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
 vendor/hisense/AD683G/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
 vendor/hisense/AD683G/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
 vendor/hisense/AD683G/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
 vendor/hisense/AD683G/proprietary/lib/libdsm.so:system/lib/libdsm.so \
 vendor/hisense/AD683G/proprietary/lib/libqueue.so:system/lib/libqueue.so \
 vendor/hisense/AD683G/proprietary/lib/libdiag.so:system/lib/libdiag.so \
 vendor/hisense/AD683G/proprietary/lib/libauth.so:system/lib/libauth.so \
 vendor/hisense/AD683G/proprietary/lib/libcm.so:system/lib/libcm.so \
 vendor/hisense/AD683G/proprietary/lib/libnv.so:system/lib/libnv.so \
 vendor/hisense/AD683G/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
 vendor/hisense/AD683G/proprietary/lib/libwms.so:system/lib/libwms.so \
 vendor/hisense/AD683G/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
 vendor/hisense/AD683G/proprietary/lib/libqmi.so:system/lib/libqmi.so \
 vendor/hisense/AD683G/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
 vendor/hisense/AD683G/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
 vendor/hisense/AD683G/proprietary/lib/libidl.so:system/lib/libidl.so \
 vendor/hisense/AD683G/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
 vendor/hisense/AD683G/proprietary/lib/libqdi.so:system/lib/libqdi.so \
 vendor/hisense/AD683G/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
 vendor/hisense/AD683G/proprietary/lib/libqdp.so:system/lib/libqdp.so \
 vendor/hisense/AD683G/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
 vendor/hisense/AD683G/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
 vendor/hisense/AD683G/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
 vendor/hisense/AD683G/proprietary/bin/cnd:system/bin/cnd \
 vendor/hisense/AD683G/proprietary/bin/netmgrd:system/bin/netmgrd \
 vendor/hisense/AD683G/proprietary/bin/qmiproxy:system/bin/qmiproxy \
 vendor/hisense/AD683G/proprietary/bin/qmuxd:system/bin/qmuxd \
 vendor/hisense/AD683G/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
 vendor/hisense/AD683G/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
 vendor/hisense/AD683G/proprietary/bin/rild:system/bin/rild \
 vendor/hisense/AD683G/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
 vendor/hisense/AD683G/proprietary/lib/libril.so:system/lib/libril.so \
 vendor/hisense/AD683G/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
 vendor/hisense/AD683G/proprietary/lib/libxml.so:system/lib/libxml.so \
 vendor/hisense/AD683G/proprietary/lib/libdnshostprio.so:system/lib/libdnshostprio.so \
 vendor/hisense/AD683G/proprietary/lib/libtcpfinaggr.so:system/lib/libtcpfinaggr.so \
 vendor/hisense/AD683G/proprietary/lib/pp_proc_plugin.so:system/lib/pp_proc_plugin.so \
 vendor/hisense/AD683G/proprietary/lib/qnet-plugin.so:system/lib/qnet-plugin.so \
 vendor/hisense/AD683G/proprietary/lib/tcp-connections.so:system/lib/tcp-connections.so \
 vendor/hisense/AD683G/proprietary/bin/rmt_storage:system/bin/rmt_storage \
 vendor/hisense/AD683G/proprietary/bin/sdcard:system/bin/sdcard \
 vendor/hisense/AD683G/proprietary/bin/port-bridge:system/bin/port-bridge \
 vendor/hisense/AD683G/proprietary/etc/loc_parameter.ini:system/etc/loc_parameter.ini \
 vendor/hisense/AD683G/proprietary/lib/armeabi/libdme_main.so:system/lib/armeabi/libdme_main.so \
 vendor/hisense/AD683G/proprietary/bin/memsicd:system/bin/memsicd \
 vendor/hisense/AD683G/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
 vendor/hisense/AD683G/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
 vendor/hisense/AD683G/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
 vendor/hisense/AD683G/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
 vendor/hisense/AD683G/proprietary/bin/thermald:system/bin/thermald \
 vendor/hisense/AD683G/proprietary/lib/libadc.so:system/lib/libadc.so \
 vendor/hisense/AD683G/proprietary/bin/mpdecision:system/bin/mpdecision \
 vendor/hisense/AD683G/proprietary/bin/gpu_dcvsd:system/bin/gpu_dcvsd \
 vendor/hisense/AD683G/proprietary/bin/usbhub:system/bin/usbhub \
 vendor/hisense/AD683G/proprietary/bin/usbhub_init:system/bin/usbhub_init \
 vendor/hisense/AD683G/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
 vendor/hisense/AD683G/proprietary/bin/abtfilt:system/bin/abtfilt \
 vendor/hisense/AD683G/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches
